/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SkillId = IDL.Text;
export const Result_1 = IDL.Variant({ 'ok' : SkillId, 'err' : IDL.Text });
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const UserProfilePublic = IDL.Record({
  'creditsEarned' : IDL.Nat,
  'credits' : IDL.Nat,
  'userId' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'languages' : IDL.Vec(IDL.Text),
  'skillCount' : IDL.Nat,
  'rating' : IDL.Float64,
});
export const LeaderboardSort = IDL.Variant({
  'creditsEarned' : IDL.Null,
  'skillCount' : IDL.Null,
  'rating' : IDL.Null,
});
export const LeaderboardEntry = IDL.Record({
  'creditsEarned' : IDL.Nat,
  'userId' : UserId,
  'name' : IDL.Text,
  'skillCount' : IDL.Nat,
  'avgRating' : IDL.Float64,
});
export const SkillWithMeta = IDL.Record({
  'title' : IDL.Text,
  'skillId' : SkillId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'audioUrl' : IDL.Text,
  'creatorName' : IDL.Text,
  'durationSeconds' : IDL.Nat,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'isUnlocked' : IDL.Bool,
});
export const SkillFilter = IDL.Record({
  'tag' : IDL.Opt(IDL.Text),
  'search' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(IDL.Text),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSkill' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
      [Result_1],
      [],
    ),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeaderboard' : IDL.Func(
      [LeaderboardSort, IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMyCredits' : IDL.Func([], [IDL.Nat], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
  'getMySkills' : IDL.Func([], [IDL.Vec(SkillWithMeta)], ['query']),
  'getSkill' : IDL.Func([SkillId], [IDL.Opt(SkillWithMeta)], ['query']),
  'getSkillRating' : IDL.Func([SkillId], [IDL.Float64], ['query']),
  'getUserProfile' : IDL.Func(
      [UserId],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUnlocked' : IDL.Func([SkillId], [IDL.Bool], ['query']),
  'listSkills' : IDL.Func([SkillFilter], [IDL.Vec(SkillWithMeta)], ['query']),
  'rateSkill' : IDL.Func([SkillId, IDL.Nat], [Result], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'saveMyProfile' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'unlockSkill' : IDL.Func([SkillId], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SkillId = IDL.Text;
  const Result_1 = IDL.Variant({ 'ok' : SkillId, 'err' : IDL.Text });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const UserProfilePublic = IDL.Record({
    'creditsEarned' : IDL.Nat,
    'credits' : IDL.Nat,
    'userId' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'languages' : IDL.Vec(IDL.Text),
    'skillCount' : IDL.Nat,
    'rating' : IDL.Float64,
  });
  const LeaderboardSort = IDL.Variant({
    'creditsEarned' : IDL.Null,
    'skillCount' : IDL.Null,
    'rating' : IDL.Null,
  });
  const LeaderboardEntry = IDL.Record({
    'creditsEarned' : IDL.Nat,
    'userId' : UserId,
    'name' : IDL.Text,
    'skillCount' : IDL.Nat,
    'avgRating' : IDL.Float64,
  });
  const SkillWithMeta = IDL.Record({
    'title' : IDL.Text,
    'skillId' : SkillId,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'audioUrl' : IDL.Text,
    'creatorName' : IDL.Text,
    'durationSeconds' : IDL.Nat,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'isUnlocked' : IDL.Bool,
  });
  const SkillFilter = IDL.Record({
    'tag' : IDL.Opt(IDL.Text),
    'search' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(IDL.Text),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSkill' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text)],
        [Result_1],
        [],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeaderboard' : IDL.Func(
        [LeaderboardSort, IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMyCredits' : IDL.Func([], [IDL.Nat], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], []),
    'getMySkills' : IDL.Func([], [IDL.Vec(SkillWithMeta)], ['query']),
    'getSkill' : IDL.Func([SkillId], [IDL.Opt(SkillWithMeta)], ['query']),
    'getSkillRating' : IDL.Func([SkillId], [IDL.Float64], ['query']),
    'getUserProfile' : IDL.Func(
        [UserId],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUnlocked' : IDL.Func([SkillId], [IDL.Bool], ['query']),
    'listSkills' : IDL.Func([SkillFilter], [IDL.Vec(SkillWithMeta)], ['query']),
    'rateSkill' : IDL.Func([SkillId, IDL.Nat], [Result], []),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'saveMyProfile' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'unlockSkill' : IDL.Func([SkillId], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };