/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LeaderboardEntry {
  'creditsEarned' : bigint,
  'userId' : UserId,
  'name' : string,
  'skillCount' : bigint,
  'avgRating' : number,
}
export type LeaderboardSort = { 'creditsEarned' : null } |
  { 'skillCount' : null } |
  { 'rating' : null };
export type Result = { 'ok' : null } |
  { 'err' : string };
export type Result_1 = { 'ok' : SkillId } |
  { 'err' : string };
export interface SkillFilter {
  'tag' : [] | [string],
  'search' : [] | [string],
  'category' : [] | [string],
}
export type SkillId = string;
export interface SkillWithMeta {
  'title' : string,
  'skillId' : SkillId,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'audioUrl' : string,
  'creatorName' : string,
  'durationSeconds' : bigint,
  'category' : string,
  'rating' : number,
  'isUnlocked' : boolean,
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfilePublic {
  'creditsEarned' : bigint,
  'credits' : bigint,
  'userId' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'languages' : Array<string>,
  'skillCount' : bigint,
  'rating' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSkill' : ActorMethod<
    [string, string, string, Array<string>],
    Result_1
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeaderboard' : ActorMethod<
    [LeaderboardSort, bigint],
    Array<LeaderboardEntry>
  >,
  'getMyCredits' : ActorMethod<[], bigint>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getMySkills' : ActorMethod<[], Array<SkillWithMeta>>,
  'getSkill' : ActorMethod<[SkillId], [] | [SkillWithMeta]>,
  'getSkillRating' : ActorMethod<[SkillId], number>,
  'getUserProfile' : ActorMethod<[UserId], [] | [UserProfilePublic]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUnlocked' : ActorMethod<[SkillId], boolean>,
  'listSkills' : ActorMethod<[SkillFilter], Array<SkillWithMeta>>,
  'rateSkill' : ActorMethod<[SkillId, bigint], Result>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'saveMyProfile' : ActorMethod<[string, Array<string>], undefined>,
  'unlockSkill' : ActorMethod<[SkillId], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];